#!/bin/bash

#This program is free software: you can redistribute it and/or
#modify it under the terms of the WTFPL

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

x=`date +%s`
while true
do
  frame="$HOME/screencast/$x.png"
  screencapture -x $frame
  sleep 20
  x=`date +%s`
done
