#!/bin/bash

#This program is free software: you can redistribute it and/or
#modify it under the terms of the WTFPL

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

capcmd='__unknown__'
screencast_dir='__unknown__'
freq=20

while getopts ":d:f:" opt; do
  case $opt in
    d) screencast_dir="$OPTARG";;
    f) freq="$OPTARG";;
    ?) printf "Usage: %s [-d directory] [-f frequency] \n" $0
        exit 2;;
  esac
done

hash scrot 2>&- 
if [ $? -eq 0 ] 
then 
  capcmd='scrot -m'
fi 

hash screencapture 2>&-
if [ $? -eq 0 ] 
then 
  capcmd='screencapture -x'
fi

if [ "$capcmd" != '__unknown__' ]
then
  if [ "$screencast_dir" == '__unknown__' ]
  then
    screencast_dir="$HOME/screencast"
  fi

  if [ ! -d $screencast_dir ]
  then
    mkdir $screencast_dir 
  fi

  while true
  do
    timestamp=`date +%s`
    frame="$screencast_dir/$timestamp.png"
    $capcmd $frame
    sleep $freq
  done
else
  echo "No known screen capture applications installed."
  echo "Try installing screencapture or scrot."
fi
